import turtle

# Function to draw the letters
def draw_letter(letter):
    if letter == ' ':
        turtle.penup()
        turtle.forward(20)
    elif letter == 'A':
        turtle.down()
        turtle.left(60)
        turtle.forward(100)
        turtle.right(120)
        turtle.forward(100)
        turtle.backward(50)
        turtle.right(120)
        turtle.backward(50)
        turtle.penup()
        turtle.right(180)
        turtle.forward(50)
        turtle.left(60)
        turtle.down()
        turtle.forward(50)
        turtle.penup()
        turtle.backward(50)
        turtle.right(120)
        turtle.down()
        turtle.forward(50)
        turtle.penup()
        turtle.left(60)
        turtle.backward(50)
        turtle.left(30)
        turtle.forward(50)
    elif letter == 'B':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.circle(-25, 180)
        turtle.right(180)
        turtle.circle(-25, 180)
        turtle.backward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.down()
        turtle.forward(50)
        turtle.penup()
        turtle.left(180)
        turtle.forward(50)
        turtle.left(90)
        turtle.down()
        turtle.forward(50)
        turtle.penup()
        turtle.backward(100)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
    elif letter == 'C':
        turtle.down()
        turtle.circle(50, -180)
        turtle.penup()
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(180)
    elif letter == 'Y':
        turtle.down()
        turtle.left(60)
        turtle.forward(50)
        turtle.backward(50)
        turtle.right(120)
        turtle.forward(50)
        turtle.penup()
        turtle.left(60)
        turtle.backward(50)
        turtle.left(90)
        turtle.down()
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.backward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.backward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.penup()
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
    elif letter == 'E':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.backward(100)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.backward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.backward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
    elif letter == 'N':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.right(135)
        turtle.forward(140)
        turtle.left(135)
        turtle.forward(100)
        turtle.penup()
        turtle.backward(100)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
    elif letter == 'O':
        turtle.down()
        turtle.circle(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(180)
    elif letter == 'S':
        turtle.down()
        turtle.circle(25, 180)
        turtle.circle(25, -180)
        turtle.penup()
        turtle.backward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
    elif letter == 'R':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.circle(-25, 180)
        turtle.right(180)
        turtle.circle(-25, 180)
        turtle.backward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
    elif letter == '!':
        turtle.down()
        turtle.left(90)
        turtle.forward(50)
        turtle.backward(25)
        turtle.right(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(25)
        turtle.backward(50)
        turtle.left(90)
        turtle.forward(25)
        turtle.backward(25)
        turtle.left(90)
        turtle.penup()
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(25)
        turtle.left(90)
        turtle.down()
        turtle.circle(25)
        turtle.penup()
        turtle.backward(25)
        turtle.right(90)
        turtle.backward(50)
        turtle.left(90)
    elif letter == 'H':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.backward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.backward(100)
        turtle.penup()
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
    elif letter == 'p':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.circle(-25, 180)
        turtle.backward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
    elif letter == 'i':
        turtle.down()
        turtle.circle(5)
        turtle.penup()
        turtle.backward(5)
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
    elif letter == 'd':
        turtle.down()
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.circle(-25, -180)
        turtle.backward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)

# Setup the turtle
turtle.setup(800, 400)
turtle.speed(1)
turtle.bgcolor("lightpink")

# Set the initial position of the turtle
turtle.penup()
turtle.goto(-300, 0)

# Write the message
message = "Happy Birthday Cyenosaurus!"
for char in message:
    draw_letter(char)

# Hide the turtle
turtle.hideturtle()

# Keep the window open
turtle.done()